### PR TITLE
Release ansys-tools-path version 0.4.0

### PR DESCRIPTION
**Pull request by nmalsang**
Release ansys-tools-path version 0.4.0

### CODE REVIEW

**Comment by nmalsang** [comment]
@RobPasMue @germa89 @koubaa Guys, if it looks good for you I will create the tag v0.4.0 on the last commit and merge the PR.

**Comment by germa89** [comment]
Hello... @nmalsang 

Normally, you won't merge back into main with the increased (released) version.

Ideally you could do:

* in `release/0.4` branch, you create a branch from it (`main/new release`)
* In `main/new release` you do the version change.
* Create a PR to merge `main/new release` to `release/0.4`.
* Approve and merge.
* Tag the latest commit in `release/0.4` as `v0.4.0`.
* Create a branch from main called `main/bump to 0.5`.
* In `main/bump to 0.5` you will upgrade the version to `0.5.dev`

Remember, you _never_ have "final" versioning in `main`, it is always `X.Y.dev`. All the release versioning (`X.Y.Z`) happens in the release branches.

**Comment by germa89** [comment]
I would probably close this PR... and follow the approach mentioned earlier....

**Comment by RobPasMue** [comment]
Agreed. Please close this PR. This is not the procedure to release.

**Pull request closed without merging**
