### PR TITLE
changed hardcoded paths to os.path.join()

### LINKED ISSUE #13: Replace hardcoded paths by os.path.join
As the title. Requested internally.

### PR DESCRIPTION
**Pull request by klmcadams**
Replaced hardcoded paths with os.path.join(). Closes #13

### CODE REVIEW

**Comment by Gryfenfer97** [comment]
You may have to change the README for the change from `test` to `tests`

**Comment by RobPasMue** [comment]
> I just merged my branch with the tests with pyfakefs so there will be conflicts. Apart from that LGTM

Yep we saw that - @klmcadams is working on it

> You may have to change the README for the change from `test` to `tests`

That's right, let's adapt the README as well @klmcadams - in order to install, users now have to perform ``python -m pip install .[tests]`` instead of ``python -m pip install .[test]``

Also, for your knowledge @Gryfenfer97 --> ``tests`` is the default target name we are giving to testing deps, that's why I changed it =)

**Comment by koubaa** [comment]
@germa89 @robpasmue @Gryfenfer97 @klmcadams the reason that `os.path.join` is considered preferable to hardcoded path separators is because it is platform neutral. The way that these paths are built/used in ansys-tools-path are completely platform-specific, though, so I don't think this is really too necessary.

**Comment by klmcadams** [comment]
> @germa89 @RobPasMue @Gryfenfer97 @klmcadams the reason that `os.path.join` is considered preferable to hardcoded path separators is because it is platform neutral. The way that these paths are built/used in ansys-tools-path are completely platform-specific, though, so I don't think this is really too necessary.

I agree. I think with @Gryfenfer97's changes, I'll only have to make the test -> tests changes. Making a new branch/PR soon

**Comment by koubaa** [comment]
@RobPasMue @germa89 if you agree we can close #13

**Pull request closed without merging**
